base_config: disaster_city

# Defaults
mitsuba_filename: "disaster_city"
scene_name: "simple_disaster_city"
resolution: [1920, 1080]
cm_vmin: -120
cm_vmax: -60
verbose: True
video: False

# Scene defaults
cam_position: [-6.0, 12.0, 150.0]
cam_orientation: [0.0, 0.0, 0.0]
cam_look_at: [-6.0, 12.0, 0.0]
frequency: 28e9
synthetic_array: True

# Device defaults
tx_num_rows: 4
tx_num_cols: 4
tx_vertical_spacing: 0.5
tx_horizontal_spacing: 0.5
tx_pattern: "iso"
tx_polarization: "cross"
tx_position: [0.103637, -0.192287, 5.4]
tx_orientation: [90.0, 0.0, 0.0]
rx_included: False
rx_num_rows: 1
rx_num_cols: 1
rx_vertical_spacing: 0.5
rx_horizontal_spacing: 0.5
rx_pattern: "iso"
rx_polarization: "V"
rx_position: [-3.0, -4.2, 1.5]
rx_orientation: [0.0, 0.0, 0.0]

# Ray tracing defaults
cm_max_depth: 15
cm_cell_size: [1.0, 1.0]
cm_num_samples: 6e6
path_max_depth: 2
path_num_samples: 3e6
diffraction: True
