base_config: wireless

# Use clipped double-Q learning (from TD3)
num_critic_networks: 2
target_critic_backup_type: min
exp_name: clipq
env_name: wireless-sigmap-v0

total_steps: 100000
random_steps: 5000
training_starts: 3

batch_size: 2
replay_buffer_capacity: 1000000

discount: 0.99
use_soft_target_update: true
soft_target_update_rate: 0.005

actor_gradient_type: reparametrize
num_critic_updates: 1

use_entropy_bonus: true
temperature: 0.05
