base_config: wireless

exp_name: sac_beamforming
env_name: wireless-sigmap-v2

replay_buffer_capacity: 10500
total_steps: 10000
random_steps: 257
training_starts: 257

# Training settings
actor_learning_rate: 0.0004
actor_learning_rate: 0.0004
critic_learning_rate: 0.0003
batch_size: 256
num_train_steps_per_env_step: 5

# Actor-critic configuration
hidden_sizes: [128, 128, 128, 128]
discount: 0.1
ema_decay: 0.995 # soft_target_update_rate
num_critics: 2
num_critic_updates: 5
temperature: 0.05
num_actor_samples: 10
saved_path: "./assets/saved_models/sac_beamforming"
seed: 0
